name: Java DevOps CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Compilar y ejecutar pruebas
        run: mvn test

      - name: Generar JAR
        run: mvn package

      - name: Ejecutar aplicación
        run: java -jar target/java-devops-1.0.0.jar

      - name: Simular Deploy
        run: echo "Desplegando aplicación Java"

      - name: Login en GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir imagen Docker
        run: |
          docker build \
          -t ghcr.io/victor1997h/java-devops:1.0.0 .

      - name: Publicar imagen
        run: |
          docker push \
          ghcr.io/victor1997h/java-devops:1.0.0